language: node_js
node_js:
  - 'stable'
install: npm install
services:
  - postgresql
script: npm test
before_script:
  - psql -c 'create database mazus_ah_backend_test;' -U postgres
after_success:
  - 'npm run coveralls'
